/* Prova de operação do Command Center: passa por todas as telas com dados realistas.
   Cada verificação imprime OK/FALHA com o que foi checado. */
import { chromium } from '/opt/node22/lib/node_modules/playwright/index.mjs'
const S = process.env.S, B = 'http://127.0.0.1:8800/ops'
const br = await chromium.launch()
const ctx = await br.newContext({ viewport: { width: 1440, height: 950 } })
const pg = await ctx.newPage()
const erros = [], falhas = []
pg.on('pageerror', e => erros.push('pageerror: ' + e.message))
pg.on('console', m => { if (m.type() === 'error' && !/favicon|ERR_CONNECTION_RESET|401/.test(m.text())) erros.push('console: ' + m.text()) })
let n = 0
const ok = (nome, cond, detalhe = '') => { n++; const s = cond ? 'OK  ' : 'FALHA'; if (!cond) falhas.push(nome); console.log(`${s} ${nome}${detalhe ? ' — ' + detalhe : ''}`) }
const txt = async (sel) => (await pg.textContent(sel).catch(() => '') || '').replace(/\s+/g, ' ').trim()
const corpo = async () => txt('body')
const entra = async (email, senha = 'senha-de-teste-123') => {
  await ctx.clearCookies(); await pg.goto(B + '/login'); await pg.waitForSelector('#email')
  await pg.fill('#email', email); await pg.fill('#pw', senha)
  await pg.click('button.primary'); await pg.waitForSelector('.kpi, .banner.crit', { timeout: 15000 })
}

console.log('\n== LOGIN E SESSÃO ==')
await pg.goto(B + '/login'); await pg.fill('#email', 'italo@urace.us'); await pg.fill('#pw', 'errada'); await pg.click('button.primary')
await pg.waitForTimeout(1200)
ok('senha errada é recusada', !/Dashboard/i.test(await corpo()) || /inválid|incorret|erro/i.test(await corpo()))
await entra('italo@urace.us')
ok('login do admin entra no dashboard', (await corpo()).includes('Dashboard'))

console.log('\n== DASHBOARD ==')
const kpis = await pg.$$eval('.kpi', xs => xs.map(x => x.textContent.replace(/\s+/g, ' ').trim()))
ok('faixa de números aparece', kpis.length >= 6, `${kpis.length} indicadores`)
ok('Pista hoje / próximos 7 dias', kpis.join(' ').includes('Pista hoje') && kpis.join(' ').includes('Próximos 7 dias'))
ok('integrações listadas com nome legível', (await corpo()).includes('DocuSign') && (await corpo()).includes('QuickBooks'))
ok('DocuSign com erro aparece', /ERROR|error/i.test(await txt('.card')) || (await corpo()).includes('ERROR'))
await pg.screenshot({ path: `${S}/t01-dashboard.png`, fullPage: true })

console.log('\n== PRECISA DE ATENÇÃO ==')
await pg.goto(B + '/attention'); await pg.waitForSelector('.att')
const atts = await pg.$$eval('.att', xs => xs.map(x => x.textContent.replace(/\s+/g, ' ').trim()))
ok('há itens de atenção', atts.length >= 3, `${atts.length} itens`)
const todosAtt = atts.join(' | ')
ok('invoice vencida traz nome, valor e vencimento', /1077/.test(todosAtt) && /Carla Mendes/.test(todosAtt) && /\$819/.test(todosAtt))
ok('invoice traz o serviço no detalhe', /Urace Daily 2 stroke/.test(todosAtt))
ok('tarefa vencida traz coluna e subtarefas', /SATURDAY/.test(todosAtt) && /9\/12/.test(todosAtt))
ok('waiver devolvida identificada', /Matthew Hubbard|devolveu/i.test(todosAtt))
ok('links do sistema em cada item', (await pg.$$('.att .syslink')).length >= 2)
ok('filtros por nível existem', (await pg.$$('.tabs button')).length >= 5)
await pg.screenshot({ path: `${S}/t02-atencao.png`, fullPage: true })
await pg.click('.att >> nth=0 >> text=Instruir a IA'); await pg.waitForSelector('.balao textarea')
ok('balão Instruir a IA abre', true)
await pg.click('.balao >> text=cancelar')

console.log('\n== CLIENTES ==')
await pg.goto(B + '/clients'); await pg.waitForSelector('.tbl tbody tr')
let linhas = await pg.$$eval('.tbl tbody tr', xs => xs.map(x => x.textContent.replace(/\s+/g, ' ').trim()))
ok('lista carrega os clientes', linhas.length >= 5, `${linhas.length} linhas`)
ok('e-mail sai limpo (sem email%3a)', !linhas.join(' ').includes('%3a') && linhas.join(' ').includes('pablosantiago@outlook.com'))
ok('próximo serviço com contagem', /HOJE|AMANHÃ|em \d+ d/.test(linhas.join(' ')))
ok('duplicado Alonso/Alonzo é sugerido', (await corpo()).includes('Possíveis duplicados') || (await corpo()).includes('duplicados'))
ok('botão de puxar histórico do Asana', (await corpo()).includes('Puxar histórico'))
ok('botão de unir dois clientes', (await corpo()).includes('Unir dois clientes'))
await pg.click('.tabs >> text=Pro Racing Drivers'); await pg.waitForTimeout(700)
linhas = await pg.$$eval('.tbl tbody tr', xs => xs.map(x => x.textContent))
ok('aba Pro mostra só os Pro', linhas.length === 1 && linhas[0].includes('Bryan Santiago'), `${linhas.length} piloto(s)`)
await pg.screenshot({ path: `${S}/t03-clientes.png`, fullPage: true })

console.log('\n== CARD DO CLIENTE (Bryan, Pro mensal) ==')
await pg.goto(B + '/clients/1'); await pg.waitForSelector('.c360-h'); await pg.waitForTimeout(600)
const cab = await txt('.c360-h')
ok('cabeçalho traz piloto, responsável e idade', cab.includes('Bryan Santiago') && cab.includes('Pablo Santiago') && /idade/.test(cab))
ok('e-mail principal e alternativo', cab.includes('pablosantiago@outlook.com') && cab.includes('bryanlsantiago@outlook.com'))
ok('marca de Pro Racing Driver', cab.includes('Pro Racing Driver'))
ok('sem fila de links no topo', (await pg.$$('.c360-h .syslink')).length === 0)
const k5 = await pg.$$eval('.c360-k .kpi', xs => xs.map(x => x.textContent.replace(/\s+/g, ' ')))
ok('cinco números no card', k5.length === 5, k5.length + ' cartões')
ok('valor em aberto do QBO no card', k5.join(' ').includes('3,156.90') || k5.join(' ').includes('3156'))
const abas = await pg.$$eval('.tabs button', xs => xs.map(x => x.textContent.trim()))
ok('abas de Pro (equipamento e corridas)', abas.some(a => a.includes('Equipamento')) && abas.some(a => a.includes('Corridas')))
const tl = await txt('.tl')
ok('linha do tempo agrupada por mês', (await pg.$$('.tl-m')).length >= 1)
ok('cada evento com seu link', (await pg.$$('.tl .syslink')).length >= 3, (await pg.$$('.tl .syslink')).length + ' links')
ok('invoice na linha do tempo com valor', /Invoice 1044/.test(tl) && /\$3,156.90/.test(tl))
await pg.screenshot({ path: `${S}/t04-card.png`, fullPage: true })
for (const [aba, esperado] of [['Mensalidade', /sess|invoice|plano/i], ['Equipamento', /Chassi|Motor/i], ['Corridas', /ROK|Nenhuma corrida/i], ['Serviços', /Academy/], ['Waivers', /parental/], ['E-mails', /Karting|Nenhum/], ['Invoices', /1044/]]) {
  const b = (await pg.$$('.tabs button')).find(async () => true)
  await pg.click(`.tabs >> text=${aba}`).catch(() => {}); await pg.waitForTimeout(500)
  ok(`aba ${aba} carrega`, esperado.test(await txt('.card.card-b')))
}
await pg.click('.tabs >> text=Equipamento'); await pg.waitForTimeout(500)
ok('catálogo editável dentro do card', (await corpo()).includes('Cadastrar ou editar chassis'))

console.log('\n== CORRIDAS (calendário) ==')
await pg.goto(B + '/races'); await pg.waitForSelector('.cal')
ok('calendário mensal renderiza', (await pg.$$('.cal-c')).length >= 28)
const evs = await pg.$$eval('.cal-ev', xs => xs.map(x => x.textContent))
ok('corrida no calendário', evs.some(e => e.includes('ROK')), evs.length + ' evento(s)')
ok('só corridas, sem treinos', !evs.some(e => /Academy|Daily|Coaching/.test(e)))
ok('contagem de confirmados no chip', evs.join(' ').includes('★'))
await pg.click('.cal-ev >> nth=0'); await pg.waitForSelector('.modal'); await pg.waitForTimeout(600)
const md = await txt('.modal')
ok('modal traz pilotos e situação', md.includes('Bryan Santiago') && /confirmado/.test(md))
ok('modal traz prévia de custo', md.includes('prévia de custo') || md.includes('Prévia'))
ok('modal aponta as subtarefas do modelo', md.includes('Subtarefas'))
await pg.screenshot({ path: `${S}/t05-corridas.png`, fullPage: true })
await pg.click('.modal .close')
await pg.click('text=+ Nova corrida'); await pg.waitForSelector('.modal')
ok('Nova corrida cita o modelo New Race', (await txt('.modal')).includes('New Race'))
await pg.click('.modal .close')

console.log('\n== SISTEMAS ==')
await pg.goto(B + '/asana'); await pg.waitForTimeout(900)
ok('Asana: quadro por coluna', /SUNDAY|SATURDAY/.test(await corpo()))
ok('Asana: botão de nova tarefa', (await corpo()).includes('Nova tarefa'))
await pg.goto(B + '/docusign'); await pg.waitForTimeout(900)
ok('DocuSign: envelopes na tela', /Pablo Santiago|Matthew Hubbard/.test(await corpo()))
ok('DocuSign: devolvida sinalizada', /devolv|autoresponded/i.test(await corpo()))
await pg.goto(B + '/gmail'); await pg.waitForSelector('.mail'); await pg.waitForTimeout(900)
ok('Gmail: três colunas', (await pg.$$('.mail .labels')).length === 1 && (await pg.$$('.mail .list')).length === 1)
ok('Gmail: thread na inbox', (await corpo()).includes('Posso trocar o dia do treino'))
ok('Gmail: botão de triar com a IA', (await corpo()).includes('Triar com a IA'))
await pg.click('.mail .item:has-text("Posso trocar") .subj'); await pg.waitForTimeout(900)
ok('Gmail: chips de marcador clicáveis', (await pg.$$('.mail .toolbar .lchip')).length >= 1)
await pg.click('.lpick input'); await pg.type('.lpick input', 'ka'); await pg.waitForTimeout(500)
ok('Gmail: busca de marcador por digitação', (await pg.$$('.lpick-menu')).length === 1)
await pg.keyboard.press('Escape')
await pg.screenshot({ path: `${S}/t06-gmail.png`, fullPage: true })
await pg.goto(B + '/quickbooks'); await pg.waitForTimeout(900)
ok('QuickBooks: invoices na tela', /1044|1077/.test(await corpo()))

console.log('\n== AI COMMAND (conversa) ==')
await pg.goto(B + '/ai'); await pg.waitForSelector('.msg.me'); await pg.waitForTimeout(700)
ok('conversa contínua com as mensagens do dia', (await pg.$$('.msg.me')).length >= 2)
ok('minha mensagem sem o contexto colado', !(await txt('.msg.me')).includes('O QUE O DONO JÁ ENSINOU'))
ok('resposta da IA como texto', (await corpo()).includes('Achei o histórico'))
const acts = await pg.$$eval('.act', xs => xs.map(x => x.textContent.replace(/\s+/g, ' ')))
ok('ações abaixo da resposta', acts.length >= 2, acts.length + ' ações')
ok('nome da ação legível', acts.join(' ').includes('Criar e enviar invoice') && acts.join(' ').includes('Criar tarefa'))
ok('tarefa executada mostra o resultado', acts.join(' ').includes('criada no Asana'))
ok('prévia da invoice com $500 e data do serviço', acts.join(' ').includes('$500.00') && /Serviço em/.test(acts.join(' ')))
ok('vencimento 2 dias antes aparece', acts.join(' ').includes('2 dias antes do serviço'))
ok('proposta incompleta sinalizada', acts.join(' ').includes('incompleta') || acts.join(' ').includes('Proposta incompleta'))
ok('botão Completar agora na incompleta', (await corpo()).includes('Completar agora'))
ok('lista de conversas para o admin', (await pg.$$('.hist .it')).length >= 2)
const convs = await pg.$$eval('.hist .it .t', xs => xs.map(x => x.textContent))
ok('conversa automática separada', convs.some(c => /Autom/.test(c)))
await pg.screenshot({ path: `${S}/t07-ai.png`, fullPage: true })
await pg.click('.hist .it >> nth=1'); await pg.waitForTimeout(800)
ok('admin abre a conversa de outro usuário', /Eduardo|Autom|conversa de/.test(await corpo()))

console.log('\n== APROVAÇÕES ==')
await pg.goto(B + '/approvals'); await pg.waitForSelector('.act')
const ap = await txt('body')
ok('pendentes listadas', /Criar e enviar invoice/.test(ap))
ok('prévia antes de aprovar', /PRÉVIA DA INVOICE|Prévia da invoice/i.test(ap))
ok('aprovar e enviar disponível', ap.includes('Aprovar e enviar'))
await pg.screenshot({ path: `${S}/t08-aprovacoes.png`, fullPage: true })

console.log('\n== AUTOMAÇÃO / INTEGRAÇÕES / ADMIN ==')
await pg.goto(B + '/automation'); await pg.waitForSelector('.act')
const au = await corpo()
ok('regras de automação listadas', (await pg.$$('.act')).length >= 5)
ok('triagem do Gmail com horários', au.includes('07:00') && au.includes('21:00'))
ok('sondagem de integrações 07:00 e 22:00', au.includes('22:00'))
ok('memória da IA visível', /ENSIN|memória|aprend/i.test(au))
await pg.goto(B + '/integrations'); await pg.waitForTimeout(800)
ok('integrações com estado real', (await corpo()).includes('CONNECTED') && (await corpo()).includes('ERROR'))
ok('abas de planilhas e arquivos', (await corpo()).includes('Planilhas') && (await corpo()).includes('Arquivos'))
await pg.goto(B + '/users'); await pg.waitForTimeout(800)
ok('usuários com papéis', /ADMIN/.test(await corpo()) && /MANAGER/.test(await corpo()) && /VIEWER/.test(await corpo()))
await pg.goto(B + '/audit'); await pg.waitForTimeout(800)
ok('auditoria registra eventos', (await pg.$$('.tbl tbody tr')).length >= 1)
await pg.goto(B + '/policies'); await pg.waitForTimeout(800)
ok('políticas da IA listadas', /Bloqueada/.test(await corpo()) && /Aprovação/.test(await corpo()))

console.log('\n== BUSCA RÁPIDA (Cmd+K) ==')
await pg.goto(B + '/'); await pg.waitForSelector('.kpi')
await pg.keyboard.press('Meta+k'); await pg.waitForTimeout(600)
if ((await pg.$$('.pal')).length === 0) { await pg.keyboard.press('Control+k'); await pg.waitForTimeout(600) }
ok('paleta abre', (await pg.$$('.pal')).length === 1)
await pg.keyboard.type('Bryan'); await pg.waitForTimeout(900)
ok('busca acha o piloto', (await txt('.pal')).includes('Bryan'))
await pg.keyboard.press('Escape')

console.log('\n== PAPÉIS (RBAC) ==')
await entra('op@urace.us')
await pg.goto(B + '/approvals'); await pg.waitForTimeout(900)
ok('operador não aprova invoice', !(await corpo()).includes('Aprovar e enviar'))
await pg.goto(B + '/ai'); await pg.waitForTimeout(900)
ok('operador vê só a própria conversa', (await pg.$$('.hist .it')).length === 0)
ok('operador pode escrever', (await pg.$$('.composer textarea')).length === 1)
await entra('leitor@urace.us')
await pg.goto(B + '/ai'); await pg.waitForTimeout(900)
ok('leitor não escreve no chat', (await pg.$$('.composer textarea')).length === 0)
await pg.goto(B + '/clients/1'); await pg.waitForTimeout(900)
ok('leitor não vê botão de editar', !(await txt('.c360-h')).includes('Editar'))
ok('leitor não vê invoices', /Invoices 🔒|restrito/.test(await corpo()) || !(await corpo()).includes('1044'))

console.log('\n== TEMA E CELULAR ==')
await entra('italo@urace.us')
await pg.emulateMedia({ colorScheme: 'dark' }); await pg.goto(B + '/clients/1'); await pg.waitForTimeout(900)
ok('tema escuro sem texto invisível', (await pg.evaluate(() => getComputedStyle(document.body).backgroundColor)) !== 'rgba(0, 0, 0, 0)')
await pg.screenshot({ path: `${S}/t09-escuro.png` })
await pg.setViewportSize({ width: 390, height: 844 })
await pg.goto(B + '/'); await pg.waitForSelector('.kpi'); await pg.waitForTimeout(700)
ok('celular sem rolagem lateral', await pg.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 2))
await pg.screenshot({ path: `${S}/t10-celular.png` })

console.log(`\n===== ${n - falhas.length}/${n} verificações OK =====`)
if (falhas.length) console.log('FALHAS: ' + falhas.join(' | '))
console.log('erros de página: ' + (erros.length ? erros.slice(0, 5).join(' | ') : 'nenhum'))
await br.close()
